### PR TITLE
Add Breadcrumbs support

### PR DESCRIPTION
**Pull request by hotmeteor**
Adding `@breadcrumbs` support

### CODE REVIEW

**Comment by hotmeteor** [comment]
@edalzell I can't figure this one out, but I am trying to do it with a collection. Any assistance would be ❤️

**Comment by hotmeteor** [comment]
So what I have here technically works, but it's pretty brittle against future Statamic changes.

**Comment by edalzell** [comment]
@hotmeteor could you update the readme too please?

**Comment by hotmeteor** [comment]
@edalzell Added: https://github.com/edalzell/statamic-blade/pull/37

**Comment by edalzell** [comment]
Awesome thanks, released new version!

**Pull request merged**
