### PR TITLE
Return regular view data if a route is not served by Statamic

### LINKED ISSUE #63: Laravel models are converted to arrays inside of blade components
I use Statamic along with one of my Laravel applications. I have the `AugmentationViewServiceProvider` enabled to access Statamic data inside of my Statamic views. So far everything works.

The route `/courses` is managed by Laravel and I pass all the courses to `courses/index.blade.php`. There I pass each course model to a blade component `<x-course :course="$course"/>`.

When dumping the course data in the blade view I get a perfect course model. Inside of the blade component the model is converted to an array. When disabling the `AugmentationViewServiceProvider` it works again.

Because my model extends the default Laravel model which implements the `JsonSerializable` interface, the values are augmented.
https://github.com/edalzell/statamic-blade/blob/8d741f3288f16eeeb49c1004089d1607b165936f/src/Concerns/AugmentsValues.php#L24-L26

But in my opinion the augmentation should only happen if a Statamic view is queried.

### PR DESCRIPTION
**Pull request by marcorieser**
Fixes #63

### CODE REVIEW

**Comment by marcorieser** [comment]
Maybe there is a better way to detect if a route is served by Statamic than checking for the presence of`$variables['cp_url']`.

**Comment by edalzell** [comment]
What if folks want the augmented data though?

**Comment by marcorieser** [comment]
> What if folks want the augmented data though?

When do you want to have an array of data instead of the object in Laravel views? Maybe my experience with Statamic and Laravel is too limited to think of a use case for this.

**Comment by marcorieser** [comment]
Thank you 😌

**Pull request merged**
